services:
  user-db:
    image: postgres:15
    container_name: postgres-db-users
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    ports:
      - "5433:5432"
    volumes:
      - userdb_data:/var/lib/postgresql/data
    restart: unless-stopped

  task-db:
    image: postgres:15
    container_name: postgres-db-tasks
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks_db
    ports:
      - "5434:5432"
    volumes:
      - taskdb_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-gRPC
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - user-db
      - task-db
    restart: unless-stopped

volumes:
  userdb_data:
  taskdb_data:
